id: P84D363D6
initial_creation_type: input
source_metadata:
  Title: Pre-Dinnaga Budhist texts on Logic
  Editor: Tucci, G.
  Publisher: Pilgrims Book House
  Place of Publication: Nepal
  Year: '1998'
  Atha prathamaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha dvitīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Atha tṛtīyaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Athe caturthaṃ prakaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:51:10.020982'
last_modified_at: '2022-03-08T16:51:10.020990'
